In [ ]:
pip install dwave-ocean-sdk matplotlib openjij

     |████████████████████████████████| 711 kB 3.8 MB/s 
     |████████████████████████████████| 204 kB 49.8 MB/s 
     |████████████████████████████████| 697 kB 39.0 MB/s 
     |████████████████████████████████| 88 kB 7.7 MB/s 
     |████████████████████████████████| 3.3 MB 43.0 MB/s 
     |████████████████████████████████| 103 kB 61.5 MB/s 
     |████████████████████████████████| 87 kB 5.7 MB/s 
     |████████████████████████████████| 887 kB 60.3 MB/s 
     |████████████████████████████████| 654 kB 62.4 MB/s 
     |████████████████████████████████| 13.1 MB 63 kB/s 
     |████████████████████████████████| 397 kB 60.1 MB/s 
     |████████████████████████████████| 782 kB 48.3 MB/s 
     |████████████████████████████████| 67 kB 5.3 MB/s 
     |████████████████████████████████| 10.1 MB 43.3 MB/s 
     |████████████████████████████████| 28.5 MB 50 kB/s 
     |████████████████████████████████| 14.2 MB 57 kB/s 
     |████████████████████████████████| 1.2 MB 17.0 MB/s 
  Attempting uninstall:

In [ ]:
token = 'xxxxx'
endpoint = 'https://cloud.dwavesys.com/sapi/'

In [ ]:
from dwave.system import DWaveSampler, EmbeddingComposite
from openjij import SQASampler
import numpy as np
from pyqubo import Array, Constraint, Placeholder
from dwave.system import DWaveSampler, EmbeddingComposite

N: 人数　num_of_g: group数

In [ ]:
N = 22
num_of_g = 4

隣接行列を作成

In [ ]:
A = np.zeros(N * N).reshape(N, N) 
A[0] = [0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,1,0,1]
A[1] = [0,0,1,1,0,1,0,1,0,0,0,0,1,0,0,0,1,0,1,1,0,0]
A[2] = [0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
A[3] = [1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,1]
A[4] = [0,0,0,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0]
A[5] = [0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,1,0,0,1,0]
A[6] = [0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1]
A[7] = [0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0]
A[8] = [0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,1,0,0,0]
A[9] = [0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1]
A[10] = [0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0]
A[11] = [1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,1,0,1,0,0]
A[12] = [1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0]
A[13] = [0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0]
A[14] = [0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0]
A[15] = [0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0]
A[16] = [1,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,2,0,0]
A[17] = [0,0,0,1,0,1,0,0,1,0,0,1,0,1,0,0,1,0,0,0,0,0]
A[18] = [0,1,0,0,1,0,1,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0]
A[19] = [1,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,2,0,0,0,0,0]
A[20] = [0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0]
A[21] = [1,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0]

In [ ]:
sum_vec_row = np.zeros(N)
sum_vec_col = np.zeros(N)
for i in range(N):
  total = 0
  total2 = 0
  for j in range(N):
    total += A[i][j]
    total2 += A[j][i]
  sum_vec_row[i] = total
  sum_vec_col[i] = total2
print(sum_vec_row)
print(sum_vec_col) 

[6. 8. 2. 7. 4. 6. 4. 3. 4. 3. 2. 6. 4. 3. 2. 2. 7. 6. 6. 6. 3. 4.]
[6. 8. 2. 7. 4. 6. 4. 3. 4. 3. 2. 6. 4. 3. 2. 2. 7. 6. 6. 6. 3. 4.]


In [ ]:
D = np.diag(np.sum(A, axis=0))
L = D - A

In [ ]:
x = Array.create(name='x', shape=(N, num_of_g), vartype='BINARY')

グループが異なるエッジのコスト

In [ ]:
cost = 0
for i in range(num_of_g):
  cost = cost + x.T[i] @ L @ x.T[i].T

グループ間で人数が異なるコスト

In [ ]:
constr_fair = 0
for j in range(num_of_g):
  constr1 = 0
  for i in range(N):
    constr1 += x[i][j]
  constr_fair += (constr1 - N/num_of_g) **2

一人が複数グループに含まれるペナルティ

In [ ]:
constr_onehot = 0
for i in range(N):
  constr2 = 0
  for j in range(num_of_g):
    constr2 += x[i][j]
  constr_onehot += (constr2 - 1) ** 2

In [ ]:
cost_func = cost + Placeholder('a')*Constraint(constr_fair, label="fair_penalty") + Placeholder('b')*Constraint(constr_onehot, label="onehot_penalty")

In [ ]:
model = cost_func.compile()

In [ ]:
feed_dict = {'a':2.0, 'b':3.0}
QUBO, offset = model.to_qubo(feed_dict=feed_dict)

In [ ]:
dw_sampler = DWaveSampler(solver='Advantage_system1.1', token=token, endpoint=endpoint)
sampler = EmbeddingComposite(dw_sampler)

In [ ]:
sampleset = sampler.sample_qubo(QUBO, num_reads=100)
print(sampleset.record)

[([0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0], -266., 1, 0.01136364)
 ([0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0], -258., 1, 0.02272727)
 ([0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0], -263., 1, 0.01136364)
 ([0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0

In [ ]:
sampleset.record[3][0].reshape(N, num_of_g)

array([[0, 1, 0, 0],
       [0, 0, 1, 1],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 1],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1]], dtype=int8)

In [ ]:
offset

330.0

In [ ]:
offset - 256

74.0

In [ ]:
from dwave.system import LeapHybridSampler
sampler_hybrid = LeapHybridSampler(solver='hybrid_binary_quadratic_model_version2', token=token, endpoint=endpoint)
sampleset_hybrid = sampler_hybrid.sample_qubo(QUBO)

In [ ]:
sampleset_hybrid.record[0][0].reshape(N, num_of_g)

array([[0, 1, 0, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0]], dtype=int32)

In [ ]:
print(sampleset_hybrid.record)

[([1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0], -244., 1)]


In [ ]:
offset + sampleset_hybrid.record[0][1]

40.0